server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 9090
    - type: https
      port: 9443
      keyStorePath: test.keystore
      keyStorePassword: example
    #this requires the alpn-boot library on the JVM's boot classpath
    #- type: h2
    #  port: 8445
    #  keyStorePath: test.keystore
    #  keyStorePassword: example
  adminConnectors:
    - type: http
      port: 9091
    - type: https
      port: 9444
      keyStorePath: test.keystore
      keyStorePassword: example

logging:
        level: INFO